[deploy]
startCommand = "touch database/database.sqlite && php artisan migrate --force && npx concurrently \"php artisan serve --host=0.0.0.0 --port=$PORT\" \"php artisan schedule:work\""
healthcheckPath = "/"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
